services:
  database:
    image: postgres:latest
    container_name: blazor-crud-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: blazor_crud_db
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  frontend:
    container_name: blazor-crud-app
    build:
      context: .
      dockerfile: BlazorCrud/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - database
    ports:
      - "5000:8080"

volumes:
  database_data: