name: Build and Push Blazor App Images

on:
  push:
    branches:
      - main
      - release/**  # Matches any branch starting with 'release/'
  pull_request:
    branches:
      - main
      - release/**  # Matches PRs into any 'release/' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Adjust based on your project

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build the App
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --no-build --configuration Release

      - name: Publish Blazor App
        run: dotnet publish -c Release -o publish_output

      # Extract version from .csproj
      - name: Get Version from .csproj
        id: get_version
        run: |
          VERSION=$(grep -oP '(?<=<Version>)(.*)(?=</Version>)' **/*.csproj)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

  push_image:
    needs: build
    if: startsWith(github.ref, 'refs/heads/release/')  # Check for any 'release/' branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      # Check if the Docker image with the version already exists
      - name: Check if Docker Image Exists on Docker Hub
        id: check_image_exists
        run: |
          IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/blazor-frontend:${{ env.VERSION }}"
          if docker manifest inspect $IMAGE_TAG > /dev/null 2>&1; then
            echo "Image $IMAGE_TAG already exists. Skipping push."
            exit 1  # Fails the job if the image with version ${{env.VERSION}} already exists
          else
            echo "Image $IMAGE_TAG does not exist. Proceeding with build."
          fi

      - name: Build and Push Docker frontend Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: guillenmartins/blazor-frontend
          dockerfile: 'BlazorCrud/Dockerfile'
          tags: ${{ env.VERSION }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}